### ISSUE TITLE
Player variable not replacing

### ISSUE THREAD

**Issue by onlyjot** [Nuckerr/HypixelHello#1]
I was looking forward to using this excellent plugin on my Hypixel remake when I came across the issue of the command saying "Why hello there %player%" rather than the player's name. Please fix! I need this!

**Comment by Nuckerr** [comment]
Hi, thanks for your issue. Sadly I haven't been looking plugin lately so I will work on a 2.0 redo as I have a learnt a lot more on plugin development. I'll be to add that to the release.
